version: '3.8'
services:
  postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
